### ISSUE TITLE
remove dependency on ftw.upgrade?

### ISSUE THREAD

**Issue by davisagli** [4teamwork/collective.deletepermission#13]
Would you be willing to remove the dependency on ftw.upgrade? This package looks useful, but ftw.upgrade pulls in a number of dependencies of its own that I'd prefer not to add to my project when I don't really need them.

**Comment by jone** [comment]
Yes, that is quite easily possible.
Currently we are not using much of ftw.upgrade, the upgrade step can easily be changed to be just a function (standard Plone style).
I'll not be able to change this in the next weeks since I'm on vacations, but feel free to make a pull-request :wink:

**Comment by maethu** [comment]
@davisagli I've just released ``collective.deletepermission`` 1.2.1 (Removed ftw.upgrade dependency.)

**Comment by davisagli** [comment]
Thanks!
